// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/happenin/Discover.tsx": () => import("../components/mockups/happenin/Discover.tsx"),
  "./components/mockups/happenin/EventChat.tsx": () => import("../components/mockups/happenin/EventChat.tsx"),
  "./components/mockups/happenin/EventDetail.tsx": () => import("../components/mockups/happenin/EventDetail.tsx"),
  "./components/mockups/happenin/Landing.tsx": () => import("../components/mockups/happenin/Landing.tsx"),
  "./components/mockups/happenin/Login.tsx": () => import("../components/mockups/happenin/Login.tsx"),
  "./components/mockups/happenin/OrganizerHub.tsx": () => import("../components/mockups/happenin/OrganizerHub.tsx"),
  "./components/mockups/happenin/SignUp.tsx": () => import("../components/mockups/happenin/SignUp.tsx"),
  "./components/mockups/happenin/TicketCheckout.tsx": () => import("../components/mockups/happenin/TicketCheckout.tsx"),
  "./components/mockups/happenin/TicketConfirmation.tsx": () => import("../components/mockups/happenin/TicketConfirmation.tsx")
};
