// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/happenin/Discover.tsx": () => import("../components/mockups/happenin/Discover.tsx"),
  "./components/mockups/happenin/Landing.tsx": () => import("../components/mockups/happenin/Landing.tsx")
};
